// app/connections/page.tsx
"use client";

import { formatDistanceToNow } from "date-fns";
import { Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { RenameConnectionDialog } from "@/components/connections/rename-connection-dialog";
import { AddConnectionOverlay } from "@/components/overlays/add-connection-overlay";
import { useOverlay } from "@/components/overlays/overlay-provider";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { IntegrationIcon } from "@/components/ui/integration-icon";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { type AppConnection, api } from "@/lib/api-client";
import { AppConnectionType } from "@/lib/types/app-connection";

function getStatusBadge(status: string) {
  switch (status) {
    case "ACTIVE":
      return (
        <Badge className="border-transparent bg-emerald-500/10 text-emerald-600">
          Active
        </Badge>
      );
    case "ERROR":
      return <Badge variant="destructive">Error</Badge>;
    default:
      return <Badge variant="secondary">Missing</Badge>;
  }
}

function isOAuth2Connection(conn: AppConnection): boolean {
  return (
    conn.type === AppConnectionType.OAUTH2 ||
    conn.type === AppConnectionType.PLATFORM_OAUTH2
  );
}

function getPieceDisplayName(pieceName: string): string {
  return pieceName
    .replace("@activepieces/piece-", "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export default function ConnectionsPage() {
  const { open } = useOverlay();
  const [connections, setConnections] = useState<AppConnection[]>([]);
  const [loading, setLoading] = useState(true);
  const [deleteTarget, setDeleteTarget] = useState<AppConnection | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [renameTarget, setRenameTarget] = useState<AppConnection | null>(null);
  // Map of pieceName (full or short) → logoUrl for IntegrationIcon
  const [pieceLogos, setPieceLogos] = useState<Map<string, string>>(new Map());

  const fetchConnections = useCallback(async () => {
    try {
      const result = await api.appConnection.list();
      setConnections(result.data);
    } catch (error) {
      console.error("Failed to fetch connections:", error);
      toast.error("Failed to load connections");
    } finally {
      setLoading(false);
    }
  }, []);

  // Fetch piece metadata for logo URLs
  useEffect(() => {
    api.piece
      .list()
      .then((pieces) => {
        const map = new Map<string, string>();
        for (const p of pieces) {
          if (p.logoUrl) {
            map.set(p.name, p.logoUrl);
            // Also map the short name
            const short = p.name.replace(/^@activepieces\/piece-/, "");
            map.set(short, p.logoUrl);
          }
        }
        setPieceLogos(map);
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    fetchConnections();
  }, [fetchConnections]);

  const handleAddConnection = () => {
    open(AddConnectionOverlay, {
      onSuccess: () => {
        fetchConnections();
      },
    });
  };

  const handleReconnect = (conn: AppConnection) => {
    open(AddConnectionOverlay, {
      preselectedPieceName: conn.pieceName,
      onSuccess: () => {
        fetchConnections();
      },
    });
  };

  const handleDelete = async () => {
    if (!deleteTarget) {
      return;
    }
    try {
      setDeleting(true);
      await api.appConnection.delete(deleteTarget.id);
      toast.success("Connection deleted");
      setDeleteTarget(null);
      fetchConnections();
    } catch (error) {
      console.error("Failed to delete connection:", error);
      toast.error("Failed to delete connection");
    } finally {
      setDeleting(false);
    }
  };

  const handleRenameSuccess = () => {
    setRenameTarget(null);
    fetchConnections();
  };

  return (
    <div className="pointer-events-auto mx-auto max-w-5xl p-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="font-semibold text-2xl">Connections</h1>
          <p className="text-muted-foreground text-sm">
            Manage your app connections and credentials
          </p>
        </div>
        <Button onClick={handleAddConnection}>
          <Plus className="mr-2 size-4" />
          New Connection
        </Button>
      </div>

      {loading ? (
        <div className="py-12 text-center text-muted-foreground text-sm">
          Loading connections...
        </div>
      ) : connections.length === 0 ? (
        <div className="py-12 text-center">
          <p className="text-muted-foreground text-sm">
            No connections yet. Add one to get started.
          </p>
        </div>
      ) : (
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>App</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Updated</TableHead>
                <TableHead className="w-[120px]" />
              </TableRow>
            </TableHeader>
            <TableBody>
              {connections.map((conn) => (
                <TableRow key={conn.id}>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <IntegrationIcon
                        className="size-5 shrink-0"
                        integration={conn.pieceName}
                        logoUrl={pieceLogos.get(conn.pieceName)}
                      />
                      <span className="text-sm">
                        {getPieceDisplayName(conn.pieceName)}
                      </span>
                    </div>
                  </TableCell>
                  <TableCell className="font-medium">
                    {conn.displayName}
                  </TableCell>
                  <TableCell>{getStatusBadge(conn.status)}</TableCell>
                  <TableCell className="text-muted-foreground text-sm">
                    {conn.updatedAt
                      ? formatDistanceToNow(new Date(conn.updatedAt), {
                          addSuffix: true,
                        })
                      : "—"}
                  </TableCell>
                  <TableCell>
                    <TooltipProvider delayDuration={300}>
                      <div className="flex items-center gap-1">
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              onClick={() => setRenameTarget(conn)}
                              size="icon"
                              variant="ghost"
                            >
                              <Pencil className="size-4" />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>Rename</TooltipContent>
                        </Tooltip>

                        {isOAuth2Connection(conn) && (
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                onClick={() => handleReconnect(conn)}
                                size="icon"
                                variant="ghost"
                              >
                                <RefreshCw className="size-4" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Reconnect</TooltipContent>
                          </Tooltip>
                        )}

                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              className="text-destructive hover:text-destructive"
                              onClick={() => setDeleteTarget(conn)}
                              size="icon"
                              variant="ghost"
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>Delete</TooltipContent>
                        </Tooltip>
                      </div>
                    </TooltipProvider>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      <AlertDialog
        onOpenChange={(open) => !open && setDeleteTarget(null)}
        open={!!deleteTarget}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Connection</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete{" "}
              <strong>{deleteTarget?.displayName}</strong>? Any flows currently
              using this connection <strong>will break immediately</strong>.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              disabled={deleting}
              onClick={handleDelete}
            >
              {deleting ? "Deleting..." : "Delete"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {renameTarget && (
        <RenameConnectionDialog
          connectionId={renameTarget.id}
          currentName={renameTarget.displayName}
          onOpenChange={(open) => !open && setRenameTarget(null)}
          onSuccess={handleRenameSuccess}
          open={!!renameTarget}
        />
      )}
    </div>
  );
}

// src/routes/connections/+page.svelte
<script lang="ts">
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import {
		Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter
	} from '$lib/components/ui/dialog';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Textarea } from '$lib/components/ui/textarea';
	import {
		Table, TableHeader, TableBody, TableRow, TableHead, TableCell
	} from '$lib/components/ui/table';
	import * as Popover from '$lib/components/ui/popover';
	import * as Command from '$lib/components/ui/command';
	import * as Tooltip from '$lib/components/ui/tooltip';
	import * as Select from '$lib/components/ui/select';
	import { Plus, Trash2, Loader2, Unplug, Pencil, RefreshCw, ChevronsUpDown, Check, Search } from 'lucide-svelte';

	interface Connection {
		id: string;
		externalId: string;
		pieceName: string;
		displayName: string;
		type: string;
		status: string;
		createdAt: string;
	}

	interface Piece {
		name: string;
		displayName: string;
		logoUrl: string | null;
		authType: string;
	}

	let connections: Connection[] = $state([]);
	let pieces: Piece[] = $state([]);
	let loading = $state(true);
	let showNewDialog = $state(false);
	let deleteConfirmId: string | null = $state(null);
	let saving = $state(false);

	// Rename state
	let renameDialogOpen = $state(false);
	let renameConnection: Connection | null = $state(null);
	let renameValue = $state('');
	let renaming = $state(false);

	// Form fields
	let formPieceName = $state('');
	let formDisplayName = $state('');
	let formType = $state('SECRET_TEXT');
	let formValue = $state('');
	let pieceSearchOpen = $state(false);
	let pieceSearch = $state('');

	let filteredPieces = $derived(
		pieceSearch
			? pieces.filter(p =>
					p.displayName.toLowerCase().includes(pieceSearch.toLowerCase()) ||
					p.name.toLowerCase().includes(pieceSearch.toLowerCase())
				)
			: pieces
	);

	let selectedPiece = $derived(pieces.find(p => p.name === formPieceName));

	async function loadConnections() {
		loading = true;
		try {
			const res = await fetch('/api/app-connections');
			if (res.ok) connections = await res.json();
		} catch { /* */ } finally {
			loading = false;
		}
	}

	async function loadPieces() {
		try {
			const res = await fetch('/api/pieces?auth=true');
			if (res.ok) pieces = await res.json();
		} catch { /* */ }
	}

	async function createConnection() {
		saving = true;
		try {
			const res = await fetch('/api/app-connections', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					pieceName: formPieceName,
					displayName: formDisplayName,
					type: formType,
					value: formValue
				})
			});
			if (res.ok) {
				showNewDialog = false;
				formPieceName = '';
				formDisplayName = '';
				formType = 'SECRET_TEXT';
				formValue = '';
				await loadConnections();
			}
		} finally { saving = false; }
	}

	async function deleteConnection(id: string) {
		try {
			const res = await fetch(`/api/app-connections/${id}`, { method: 'DELETE' });
			if (res.ok) connections = connections.filter(c => c.id !== id);
		} finally { deleteConfirmId = null; }
	}

	function openRenameDialog(conn: Connection) {
		renameConnection = conn;
		renameValue = conn.displayName;
		renameDialogOpen = true;
	}

	async function submitRename() {
		if (!renameConnection || !renameValue.trim()) return;
		renaming = true;
		try {
			const res = await fetch(`/api/app-connections/${renameConnection.id}`, {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ displayName: renameValue.trim() })
			});
			if (res.ok) {
				renameDialogOpen = false;
				renameConnection = null;
				await loadConnections();
			}
		} finally { renaming = false; }
	}

	function reconnectOAuth2(conn: Connection) {
		window.location.href = `/api/app-connections/oauth2/authorize?pieceName=${encodeURIComponent(conn.pieceName)}&connectionId=${encodeURIComponent(conn.id)}`;
	}

	function isOAuth2(type: string): boolean {
		return type === 'OAUTH2' || type === 'PLATFORM_OAUTH2';
	}

	function formatDate(dateStr: string): string {
		return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
	}

	function selectPiece(piece: Piece) {
		formPieceName = piece.name;
		if (!formDisplayName) formDisplayName = piece.displayName;
		formType = piece.authType === 'OAUTH2' ? 'PLATFORM_OAUTH2' : piece.authType || 'SECRET_TEXT';
		pieceSearchOpen = false;
		pieceSearch = '';
	}

	function openNewDialog() {
		showNewDialog = true;
		if (pieces.length === 0) loadPieces();
	}

	$effect(() => { loadConnections(); });
</script>

<div class="flex h-full flex-col">
	<header class="flex h-12 items-center justify-between border-b border-border px-6">
		<h1 class="text-sm font-semibold tracking-tight">Connections</h1>
		<Button size="sm" onclick={openNewDialog}>
			<Plus size={14} />
			New Connection
		</Button>
	</header>

	<div class="flex-1 overflow-auto p-6">
		{#if loading}
			<div class="flex items-center justify-center py-12">
				<Loader2 size={20} class="animate-spin text-muted-foreground" />
			</div>
		{:else if connections.length === 0}
			<div class="flex flex-col items-center justify-center py-16 text-center">
				<div class="rounded-full bg-muted p-4 mb-4">
					<Unplug size={24} class="text-muted-foreground" />
				</div>
				<h2 class="text-sm font-medium">No connections yet</h2>
				<p class="mt-1 text-xs text-muted-foreground max-w-sm">
					Create a connection to store API keys and credentials for your workflow actions.
				</p>
				<Button class="mt-4" size="sm" onclick={openNewDialog}>
					<Plus size={14} />
					New Connection
				</Button>
			</div>
		{:else}
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead>Name</TableHead>
						<TableHead>Piece</TableHead>
						<TableHead>Type</TableHead>
						<TableHead>Status</TableHead>
						<TableHead>Created</TableHead>
						<TableHead class="text-right">Actions</TableHead>
					</TableRow>
				</TableHeader>
				<TableBody>
					{#each connections as conn (conn.id)}
						<TableRow>
							<TableCell class="font-medium text-xs">{conn.displayName}</TableCell>
							<TableCell>
								<span class="font-mono text-[10px] text-muted-foreground">{conn.pieceName}</span>
							</TableCell>
							<TableCell>
								<Badge variant="outline" class="text-[9px]">{conn.type}</Badge>
							</TableCell>
							<TableCell>
								<Badge variant={conn.status === 'ACTIVE' ? 'default' : conn.status === 'ERROR' ? 'destructive' : 'secondary'} class="text-[9px]">
									{conn.status}
								</Badge>
							</TableCell>
							<TableCell class="text-xs text-muted-foreground">{formatDate(conn.createdAt)}</TableCell>
							<TableCell class="text-right">
								{#if deleteConfirmId === conn.id}
									<div class="flex items-center justify-end gap-1">
										<span class="text-[10px] text-muted-foreground">Delete?</span>
										<Button variant="destructive" size="sm" class="h-6 text-[10px]" onclick={() => deleteConnection(conn.id)}>Yes</Button>
										<Button variant="ghost" size="sm" class="h-6 text-[10px]" onclick={() => (deleteConfirmId = null)}>No</Button>
									</div>
								{:else}
									<div class="flex items-center justify-end gap-0.5">
										<Tooltip.Root>
											<Tooltip.Trigger>
												<Button variant="ghost" size="icon" class="h-7 w-7" onclick={() => openRenameDialog(conn)}>
													<Pencil size={12} />
												</Button>
											</Tooltip.Trigger>
											<Tooltip.Content>Rename</Tooltip.Content>
										</Tooltip.Root>

										{#if isOAuth2(conn.type)}
											<Tooltip.Root>
												<Tooltip.Trigger>
													<Button variant="ghost" size="icon" class="h-7 w-7" onclick={() => reconnectOAuth2(conn)}>
														<RefreshCw size={12} />
													</Button>
												</Tooltip.Trigger>
												<Tooltip.Content>Reconnect OAuth2</Tooltip.Content>
											</Tooltip.Root>
										{/if}

										<Tooltip.Root>
											<Tooltip.Trigger>
												<Button variant="ghost" size="icon" class="h-7 w-7 text-muted-foreground hover:text-destructive" onclick={() => (deleteConfirmId = conn.id)}>
													<Trash2 size={12} />
												</Button>
											</Tooltip.Trigger>
											<Tooltip.Content>Delete</Tooltip.Content>
										</Tooltip.Root>
									</div>
								{/if}
							</TableCell>
						</TableRow>
					{/each}
				</TableBody>
			</Table>
		{/if}
	</div>
</div>

<!-- New Connection Dialog -->
<Dialog open={showNewDialog} onOpenChange={(v) => { if (!v) showNewDialog = false; }}>
	<DialogContent class="sm:max-w-lg">
		<DialogHeader>
			<DialogTitle>New Connection</DialogTitle>
		</DialogHeader>
		<form class="space-y-4" onsubmit={(e) => { e.preventDefault(); createConnection(); }}>
			<!-- Piece Combobox -->
			<div class="space-y-1.5">
				<Label>Piece</Label>
				<Popover.Root bind:open={pieceSearchOpen}>
					<Popover.Trigger class="w-full">
						<Button variant="outline" class="w-full justify-between h-8 text-xs font-normal">
							{#if selectedPiece}
								<span class="flex items-center gap-2">
									{#if selectedPiece.logoUrl}
										<img src={selectedPiece.logoUrl} alt="" class="h-4 w-4 rounded" />
									{/if}
									{selectedPiece.displayName}
								</span>
							{:else}
								<span class="text-muted-foreground">Search pieces...</span>
							{/if}
							<ChevronsUpDown size={12} class="text-muted-foreground" />
						</Button>
					</Popover.Trigger>
					<Popover.Content class="w-[var(--bits-popover-anchor-width)] min-w-[400px] p-0" align="start">
						<Command.Root>
							<Command.Input placeholder="Search pieces..." bind:value={pieceSearch} class="text-xs" />
							<Command.List class="max-h-[200px]">
								<Command.Empty class="py-4 text-center text-xs text-muted-foreground">No pieces found.</Command.Empty>
								{#each filteredPieces.slice(0, 50) as piece (piece.name)}
									<Command.Item
										value={piece.name}
										onSelect={() => selectPiece(piece)}
										class="flex items-center gap-2 text-xs"
									>
										{#if piece.logoUrl}
											<img src={piece.logoUrl} alt="" class="h-4 w-4 rounded" />
										{:else}
											<div class="flex h-4 w-4 items-center justify-center rounded bg-muted text-[8px]">{piece.displayName.charAt(0)}</div>
										{/if}
										<span class="flex-1">{piece.displayName}</span>
										<Badge variant="outline" class="text-[8px] px-1">{piece.authType}</Badge>
										{#if formPieceName === piece.name}
											<Check size={12} class="text-primary" />
										{/if}
									</Command.Item>
								{/each}
							</Command.List>
						</Command.Root>
					</Popover.Content>
				</Popover.Root>
			</div>

			<!-- Display Name -->
			<div class="space-y-1.5">
				<Label for="displayName">Display Name</Label>
				<Input id="displayName" placeholder="e.g. My Slack Token" bind:value={formDisplayName} required class="text-xs" />
			</div>

			<!-- Type -->
			<div class="space-y-1.5">
				<Label>Type</Label>
				<Select.Root type="single" value={formType} onValueChange={(v) => { formType = v; }}>
					<Select.Trigger class="w-full text-xs">
						{formType.replace(/_/g, ' ')}
					</Select.Trigger>
					<Select.Content>
						<Select.Item value="SECRET_TEXT">Secret Text</Select.Item>
						<Select.Item value="BASIC_AUTH">Basic Auth</Select.Item>
						<Select.Item value="CUSTOM_AUTH">Custom Auth</Select.Item>
						<Select.Item value="OAUTH2">OAuth2</Select.Item>
						<Select.Item value="PLATFORM_OAUTH2">Platform OAuth2</Select.Item>
					</Select.Content>
				</Select.Root>
			</div>

			<!-- Secret Value (for SECRET_TEXT) -->
			{#if formType === 'SECRET_TEXT'}
				<div class="space-y-1.5">
					<Label for="value">Secret Value</Label>
					<Textarea id="value" placeholder="Enter your API key or secret..." bind:value={formValue} required class="text-xs" />
				</div>
			{/if}

			<DialogFooter>
				<Button variant="outline" type="button" onclick={() => (showNewDialog = false)}>Cancel</Button>
				<Button type="submit" disabled={saving || !formPieceName}>
					{#if saving}
						<Loader2 size={12} class="animate-spin" />
					{/if}
					Create
				</Button>
			</DialogFooter>
		</form>
	</DialogContent>
</Dialog>

<!-- Rename Dialog -->
<Dialog open={renameDialogOpen} onOpenChange={(v) => { if (!v) { renameDialogOpen = false; renameConnection = null; } }}>
	<DialogContent class="sm:max-w-sm">
		<DialogHeader>
			<DialogTitle>Rename Connection</DialogTitle>
		</DialogHeader>
		<form class="space-y-4" onsubmit={(e) => { e.preventDefault(); submitRename(); }}>
			<div class="space-y-1.5">
				<Label for="renameName">Display Name</Label>
				<Input id="renameName" bind:value={renameValue} required class="text-xs" />
			</div>
			<DialogFooter>
				<Button variant="outline" type="button" onclick={() => { renameDialogOpen = false; renameConnection = null; }}>Cancel</Button>
				<Button type="submit" disabled={renaming}>
					{#if renaming}<Loader2 size={12} class="animate-spin" />{/if}
					Rename
				</Button>
			</DialogFooter>
		</form>
	</DialogContent>
</Dialog>
